# BEGIN COPYRIGHT BLOCK
# (C) 2018 Red Hat, Inc.
# All rights reserved.
# END COPYRIGHT BLOCK

services:
  - docker

env:
  - FEDORA=28
  - FEDORA=29

install:
  - docker pull registry.fedoraproject.org/fedora:$FEDORA
  - docker run
      --name=container
      --detach
      -i
      -v $(pwd):/root/tomcatjss
      registry.fedoraproject.org/fedora:$FEDORA
  - docker exec container dnf install -y dnf-plugins-core gcc make rpm-build
  - docker exec container dnf copr -y enable ${TOMCATJSS_7_4_REPO:-@pki/10.7}
  - docker exec container dnf builddep -y --spec /root/tomcatjss/tomcatjss.spec
  - docker exec container dnf remove -y tomcat-native
  - docker exec container /root/tomcatjss/build.sh --with-timestamp --with-commit-id rpm

script:
  - docker exec container rpm -Uvh /root/build/tomcatjss/RPMS/*
